# Generated by Django 5.0.6 on 2024-06-30 13:15

import delivery.utils
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_transit', 'IN_TRANSIT'), ('delivered', 'DELIVERED'), ('canceled', 'CANCELED')], max_length=16)),
                ('expected_delivery_time', models.DateTimeField()),
                ('actual_delivery_time', models.DateField(blank=True, null=True, validators=[delivery.utils.validate_delivery_times])),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_transit', 'IN_TRANSIT'), ('delivered', 'DELIVERED'), ('canceled', 'CANCELED')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, max_length=32, validators=[django.core.validators.RegexValidator(message='enter a valid registration number', regex='^[A-Z]{2}\\d{2}[A-Za-z0-9]{6}$')])),
                ('model', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Model name must be alphanumeric and can contain spaces', regex='^[A-Za-z0-9 ]+$')])),
                ('vehicle_type', models.CharField(choices=[('bike', 'BIKE'), ('scooter', 'SCOOTER'), ('mini_van', 'MINI_VAN'), ('electric_bike', 'ELECTRIC_BIKE')], db_index=True, max_length=16)),
                ('capacity', models.CharField(max_length=64, validators=[delivery.utils.validate_capacity])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
