# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('order', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.deliverypersonprofile'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.deliveryvehicle'),
        ),
    ]
