# Generated by Django 5.0.6 on 2024-06-30 13:15

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_customers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('active_customers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('inactive_customers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_spend_per_customer', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('loyal_customers_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('new_customers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAnalytics',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_deliveries', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('successful_deliveries', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('failed_deliveries', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_delivery_time', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('delivery_fee_earned', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_orders', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_orders', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_orders', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('canceled_orders', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopularItemAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_orders', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_visits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unique_visitors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_orders', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('review_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue_by_day', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue_by_week', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue_by_month', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_daily_revenue', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_monthly_revenue', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_reviews', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_by_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reviews_by_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reviews_by_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_vendors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('active_vendors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('inactive_vendors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_items_sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
