# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('menu', '0002_initial'),
        ('order', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeranalytics',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='deliveryanalytics',
            name='delivery_person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.deliverypersonprofile'),
        ),
        migrations.AddField(
            model_name='orderanalytics',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
        migrations.AddField(
            model_name='popularitemanalytics',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='restaurantanalytics',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='revenueanalytics',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
        migrations.AddField(
            model_name='revenueanalytics',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='reviewanalytics',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='reviewanalytics',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
        migrations.AddField(
            model_name='reviewanalytics',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.vendorprofile'),
        ),
    ]
