# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscriptionplan'),
        ),
    ]
