# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0001_initial'),
        ('order', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltymember',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='loyalty_program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.loyaltymember'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.loyaltymember'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='reward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.reward'),
        ),
    ]
