# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.content'),
        ),
        migrations.AddField(
            model_name='contentmedia',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.content'),
        ),
        migrations.AddField(
            model_name='contentrating',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.content'),
        ),
        migrations.AddField(
            model_name='contentrating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='contentrating',
            unique_together={('content_id', 'user_id')},
        ),
    ]
