# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryorder'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
    ]
