# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_initial'),
        ('restaurant', '0002_initial'),
        ('review', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.review'),
        ),
        migrations.AddField(
            model_name='reviewreaction',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='reviewreaction',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('restaurant_id', 'customer_id', 'dish_id')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewreaction',
            unique_together={('review_id', 'customer_id')},
        ),
    ]
