# Generated by Django 5.0.6 on 2024-06-30 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion_type', models.CharField(choices=[('discount', 'DISCOUNT'), ('buy_one_get_one_free', 'BOGO'), ('cashback', 'CASHBACK')], db_index=True, max_length=32)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promo_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionTag',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(choices=[('holiday_spl', 'HOLIDAY_SPL'), ('summer_sale', 'SUMMER_SALE'), ('winter_discount', 'WINTER_DISCOUNT')], db_index=True, max_length=16)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-usage_date'],
            },
        ),
    ]
