# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='promotiontag',
            name='promotion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotion.promotion'),
        ),
    ]
