# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('promotion', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionusage',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='promotion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotion.promotion'),
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('promo_code', 'restaurant_id')},
        ),
    ]
