# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.vendorprofile'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurantcategory'),
        ),
        migrations.AddField(
            model_name='restauranthours',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantphoto',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantrevenue',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='restauranthours',
            unique_together={('restaurant_id', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantrevenue',
            unique_together={('restaurant_id', 'date')},
        ),
    ]
