# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menucategory'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menu.menuitemimage'),
        ),
    ]
